### ISSUE TITLE
Package license discussion

### ISSUE THREAD

**Issue by jsleslie** [UBC-MDS/mealprepR#84]
The license for our package R may be found here: [R license](https://github.com/UBC-MDS/mealprepR/blob/master/LICENSE.md)

Task:
- Examine the license for your project.
- Discuss and reason the license choice by opening issues in both Python and R repositories.
- Include a link of these issues in your final_project repository's README.md file.

Let's chime in below on our thoughts after reviewing the license

**Comment by annychih** [comment]
I took a look at the license and am happy to keep it as is. I doubt anyone will try to copy/sell it, but if they do I have no issue with this. I'm glad there's the giant clause (in ALL CAPS no less!) that we're not responsible for anything that might go awry if someone tries to download/use the package and something breaks.

Thanks for setting up this issue, @jsleslie !

**Comment by mglu123** [comment]
Agree with Anny!

**Comment by SamEdwardes** [comment]
Confirming I agree with Anny as well!

**Comment by jsleslie** [comment]
I agree with our package being shared without restriction. Happy to contribute to the open source ecosystem!
