### ISSUE TITLE
Project Proposal: README.md

### ISSUE THREAD

**Issue by annychih** [UBC-MDS/mealprepR#9]
Outline the package you would like to build in the README.md file. (This can be identical for both projects at this point in the project). In particular, your README.md should contain:
1.	a summary paragraph that describes the project at a high level
2.	a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset)
3.	a paragraph describing where your packages fit into the Python and R ecosystems (are there any other Python or R software packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well).
A reminder to include the URL to your Python and R projects' repositories in your milestone1 repo's README.md file so that we know where to find them.

- [x] Item 3 for fruits_and_veg (Luke)
- [x] Item 3 for missing_ingredients (Jarome)
- [x] Item 3 for bad_apples (Anny)
- [x] Item 3 for preprocess_recipe (Sam)

**Comment by annychih** [comment]
Hi @jsleslie , 

Here's the info for the `find_bad_apples()` function. Please feel free to edit / hack away at it! I'm pretty sure I provided more info than is actually necessary for the assignment. 

The super short version is that: The basic `describe()` (Python) and `summary()` (R) functions are good starting points for outlier detection, but they don't provide indices of the rows that actually contain the outliers, whereas the packages that are made specifically for outlier detection typically find outliers using multivariate outlier detection methods. The `find_bad_apples()` function sits in the space between these two extremes.

**Short Description**
`find_bad_apples()`: uses a univariate approach to outlier detection and returns the indices of rows within a dataframe of numeric values that contain outliers, and how many outliers the observation (row) contains (ie how many columns have outliers in that row).

**Existing Packages**   
The base R `summary()` function is a popular first function to run during the data exploration stage of a project because it returns the mean, median, minimum, and maximum of each variable in a dataset, which allows users to easily see whether there are possible outliers. However, the output of this function does not tell you which rows of data these outliers are found in, or how many outliers are present in the dataframe. 

Packages like *outliers* and *OutlierDetection* provide many more ways of detecting outliers using both univariate and multivariate outlier detection methods, and some functions such as the `outlierTest()` function from the *car* package also output the row within a dataframe which has the most extreme observation given a model. 

The *mealprepR* `find_bad_apples()` function provides more detail than the base R `summary()` function for outlier detection, but does not provide multivariate outlier detection like other functions from packages specifically made to detect outliers.

- outliers Package Documentation: https://cran.r-project.org/web/packages/outliers/outliers.pdf
- OutlierDetection Package Documentation: https://cran.r-project.org/web/packages/OutlierDetection/OutlierDetection.pdf
- car Package Documentation: https://cran.r-project.org/web/packages/car/car.pdf

**Comment by mglu123** [comment]
Short Description:

When we prepare a data frame to do the machine learning process, it is always pain to find which column is categorical or numerical values. My function will take a data frame, and detect the column index of the wanted columns (categorical or numerical). There is no similar package will have this function in R.
